# Generated by Django 4.1.3 on 2022-11-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MulQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multianswer', 'multianswer'), ('text', 'text')], max_length=50, verbose_name='type_question')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('question', models.CharField(max_length=100, verbose_name='question_text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questiontouser', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='TxtQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multianswer', 'multianswer'), ('text', 'text')], max_length=50, verbose_name='type_question')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('question', models.CharField(max_length=100, verbose_name='question_text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txtquestiontouser', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'db_table': 'txt_que',
            },
        ),
        migrations.CreateModel(
            name='TxtAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_ans', models.TextField(verbose_name='text_answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updation_date')),
                ('que', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='txtanswertoquestion', to='Feedback.txtquestion', verbose_name='question')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txtanswertouser', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'db_table': 'txt_ans',
            },
        ),
        migrations.CreateModel(
            name='MultipleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_ans', models.CharField(max_length=100, verbose_name='txt_ans')),
                ('boolean_ans', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updation_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='activation_option')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mulanswertoquestion', to='Feedback.mulquestion', verbose_name='question')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mulanswertouser', to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_ans', models.BooleanField(default=False)),
                ('txt_ans', models.TextField(verbose_name='text_answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updation_date')),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.multipleanswer', verbose_name='ans')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.mulquestion', verbose_name='que')),
            ],
        ),
    ]
