# Generated by Django 4.1.3 on 2022-11-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtanswer',
            name='writer',
        ),
        migrations.AlterField(
            model_name='txtanswer',
            name='que',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='txtanswertoquestion', to='Feedback.multipleanswer', verbose_name='question'),
        ),
    ]
