# Generated by Django 4.1.3 on 2022-11-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_remove_txtanswer_writer_alter_txtanswer_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txtanswer',
            name='que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txtanswertoquestion', to='Feedback.mulquestion', verbose_name='question'),
        ),
    ]
