# Generated by Django 4.1.3 on 2022-11-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_alter_txtanswer_que'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='txt_ans',
        ),
        migrations.AlterField(
            model_name='txtanswer',
            name='que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feedback.mulquestion', verbose_name='question'),
        ),
    ]
